datasets:
  adata_files: /data1021/xukaichen/data/CTA/pbmc.h5ad
  token_dict: token_dict.csv
  human_tfs: human_tfs.csv
  mouse_tfs: mouse_tfs.csv
  true_grn: OmniPath.csv

loss:
  name: SFMLoss
  kwargs:
    use_prior: True
    use_dag: False
    prior_pos_weight: 20.0
    prior_neg_weight: 1.0
    prior_neg_sample_ratio: 5.0
    alpha: 0.0
    rho: 0.01
    rho_max: 1e6
    update_period: 100

train:
  learning_rate: 1e-5
  weight_decay: 1e-2
  epochs_per_file: 1
  batch_size: 4
  device: cuda
  checkpoint_dir: ./checkpoints
  resume: False
  log_dir: ./logs
  log_name: pretrain.log
  log_overwrite: True
  log_interval: 1000
  use_tqdm: True
  tqdm_mininterval: 1.0
  use_amp: True
  amp_dtype: bf16
