Tome:
  name: "Tome"
  kwargs:
    # Gene column in adata.var to use for token mapping.
    # null -> use adata.var_names
    gene_key: feature_id
    max_length: 2048
    cond_dict: null
    batch_dict: null
    platform_key: assay
    species_key: null
    tissue_key: tissue
    disease_key: disease
    batch_key: dataset_id
    min_genes_per_cell: 200
    min_cells_per_gene: 3
    log_norm: True
    n_top_genes: 2000
