Tome:
  name: "Tome"
  kwargs:
    max_length: 2048
    cond_dict: null
    batch_dict: null
    simplify: False
    platform_key: null
    species_key: null
    tissue_key: tissue
    disease_key: cancer_type
    batch_key: patient
    min_genes_per_cell: 200
    min_cells_per_gene: 3
    log_norm: True
    n_top_genes: 2000
